version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: persian_analytics_backend_dev
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      # Mount source code for hot reload
      - ./app:/app/app
    environment:
      - DEBUG=True
